// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MafiaUsersClient is the client API for MafiaUsers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MafiaUsersClient interface {
	SetUser(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*ACK, error)
	GetUsersList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsersListResponse, error)
	ListenNotifications(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (MafiaUsers_ListenNotificationsClient, error)
	Disconnect(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mafiaUsersClient struct {
	cc grpc.ClientConnInterface
}

func NewMafiaUsersClient(cc grpc.ClientConnInterface) MafiaUsersClient {
	return &mafiaUsersClient{cc}
}

func (c *mafiaUsersClient) SetUser(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*ACK, error) {
	out := new(ACK)
	err := c.cc.Invoke(ctx, "/service.MafiaUsers/SetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mafiaUsersClient) GetUsersList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsersListResponse, error) {
	out := new(UsersListResponse)
	err := c.cc.Invoke(ctx, "/service.MafiaUsers/GetUsersList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mafiaUsersClient) ListenNotifications(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (MafiaUsers_ListenNotificationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MafiaUsers_ServiceDesc.Streams[0], "/service.MafiaUsers/ListenNotifications", opts...)
	if err != nil {
		return nil, err
	}
	x := &mafiaUsersListenNotificationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MafiaUsers_ListenNotificationsClient interface {
	Recv() (*Notification, error)
	grpc.ClientStream
}

type mafiaUsersListenNotificationsClient struct {
	grpc.ClientStream
}

func (x *mafiaUsersListenNotificationsClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mafiaUsersClient) Disconnect(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/service.MafiaUsers/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MafiaUsersServer is the server API for MafiaUsers service.
// All implementations must embed UnimplementedMafiaUsersServer
// for forward compatibility
type MafiaUsersServer interface {
	SetUser(context.Context, *StringRequest) (*ACK, error)
	GetUsersList(context.Context, *emptypb.Empty) (*UsersListResponse, error)
	ListenNotifications(*StringRequest, MafiaUsers_ListenNotificationsServer) error
	Disconnect(context.Context, *StringRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMafiaUsersServer()
}

// UnimplementedMafiaUsersServer must be embedded to have forward compatible implementations.
type UnimplementedMafiaUsersServer struct {
}

func (UnimplementedMafiaUsersServer) SetUser(context.Context, *StringRequest) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUser not implemented")
}
func (UnimplementedMafiaUsersServer) GetUsersList(context.Context, *emptypb.Empty) (*UsersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersList not implemented")
}
func (UnimplementedMafiaUsersServer) ListenNotifications(*StringRequest, MafiaUsers_ListenNotificationsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListenNotifications not implemented")
}
func (UnimplementedMafiaUsersServer) Disconnect(context.Context, *StringRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedMafiaUsersServer) mustEmbedUnimplementedMafiaUsersServer() {}

// UnsafeMafiaUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MafiaUsersServer will
// result in compilation errors.
type UnsafeMafiaUsersServer interface {
	mustEmbedUnimplementedMafiaUsersServer()
}

func RegisterMafiaUsersServer(s grpc.ServiceRegistrar, srv MafiaUsersServer) {
	s.RegisterService(&MafiaUsers_ServiceDesc, srv)
}

func _MafiaUsers_SetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MafiaUsersServer).SetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.MafiaUsers/SetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MafiaUsersServer).SetUser(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MafiaUsers_GetUsersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MafiaUsersServer).GetUsersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.MafiaUsers/GetUsersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MafiaUsersServer).GetUsersList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MafiaUsers_ListenNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StringRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MafiaUsersServer).ListenNotifications(m, &mafiaUsersListenNotificationsServer{stream})
}

type MafiaUsers_ListenNotificationsServer interface {
	Send(*Notification) error
	grpc.ServerStream
}

type mafiaUsersListenNotificationsServer struct {
	grpc.ServerStream
}

func (x *mafiaUsersListenNotificationsServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

func _MafiaUsers_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MafiaUsersServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.MafiaUsers/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MafiaUsersServer).Disconnect(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MafiaUsers_ServiceDesc is the grpc.ServiceDesc for MafiaUsers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MafiaUsers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.MafiaUsers",
	HandlerType: (*MafiaUsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUser",
			Handler:    _MafiaUsers_SetUser_Handler,
		},
		{
			MethodName: "GetUsersList",
			Handler:    _MafiaUsers_GetUsersList_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _MafiaUsers_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenNotifications",
			Handler:       _MafiaUsers_ListenNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
